name: Update Years of Experience

on:
  schedule:
    - cron: '0 0 1 7 *' # Runs once a year on July 1st

jobs:
  update_years:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Update years of experience
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/update_years.py
